data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/mysql
    - /var/www/html

db:
  image: mariadb
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
  mem_limit: 512m

web:
  build: web
  links:
    - db:mysql
  volumes_from:
    - data
  expose:
    - "80"
  mem_limit: 256m

lb:
  image: tutum/haproxy
  links:
    - web
  ports:
    - "80:80"
    - "81:1936"
  environment:
    OPTION: httpchk GET / HTTP/1.1\r\nHost:\ web
    HEALTH_CHECK: check inter 3000 rise 1 fall 2
  mem_limit: 128m
